language: java
jdk:
  - openjdk8
install:
  - mvn --settings bin/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
before_install:
  - export TZ=Asia/Shanghai
cache:
  directories:
    - $HOME/.m2/repository
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
stages:
  - build
  - name: release
    if: tag =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/
jobs:
  include:
    - stage: release
      name: "maven install release"
      script: echo "Deploying to GitHub releases ..." && pwd
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        on:
          tags: true
after_deploy:
  - bin/deploy.sh

env:
  global:
    - secure: "iKcIn1YWoyePVr2vcSXtiWk8U4l2GV867rfxTu+qvnF7ZJeyrOdIn/YR73OiOmUi/FVB1ok/HFaaQWmlNCvap+cykovp0hBQuY3fOLdKUnKkXsvCS4qpGfMiRvqHTDI6r8gg9Beqek6eziKoO321+Z4PX/DeyMEXnZyZSWmNdd1ce
      ZWNH7sqqEvTHeCs5cPBKLAlpQQCUI9YtzBwHJZ8DtALMw1h2MtNUEkdaQ7QSiQjQSjJfgXNp7/KKzDZh65YyvMax/Xcj2B0dnM+P0zkkqoYqlTchlWgUnw4CmN7xguR+/M5X6Q2HVTICLMv5YNImRv/vz4+y7uggBhF4s/dahaGKFwaJrkeF3WBj
      SEHptJj9tzuib+umH2XUwjwmRxPZUq9GAQIifxyQchVxeEIKxZHBL/CYR6H42AvlrZ9he3HhVrpPoY9wfO6cXX7hJqQrLXa+JyHEdH5hVWHaFmxx9sYmMchVi/09z88I+WvckOpOWP8palC4PJ20LnKaQctstPY4EuFDSg0ex0gbLDnV0k58u5GY
      Gvi/QJtxo6/yp4u24irKNa4t/HF5iAvBcGXbNFhG/bDq18Sdu4x8LqRQcXAxhN4g0dNz4f27aF7Hyim2GglAkq8hLTfEyO9PGt3IuSxVwkkT3tGy6XNyl6GgdFlbWby5ZD0tFD2SgCoayo="
    - secure: "yJkSh6jionxGg1S9WVjs1mMj1ycc5E120e7Ornbny1d7FUaxzFama+k5OddItyLDt6YNIRou0p2zoetyP2duV8Q82S87sOUJPIBqcA2MRbkEovFDPf/LFybAzMYdLBCP8RYSaR8kdlzocvinfzpc5p7MLTHqRMQV5coUDJB8TJQn4
      zihrifWYUCgR4hc+KL8+7aoLrmPrkZMztRlwqOiiaphQ6nbDGfOK1dWjgTHMMOyLIq5gXKzUwUZCwrLn/3SDIzG0NpoVl2PJSA1jD9pBVzwYLhkdtxHrL5k6YotaalCzb5j18hljTR/7o72+rlnyVYShQpnuSK/bizFXq6Wl/F/Q+K3m97Ty8C1B
      pPSEkryg6/lJtsumoHZsJahfA1jAhUC6OLwmehYNaofAP9e782bFeYHhGiyO7FxsE9WLSt2mBvhaR8DyZnIuhscE6DzqaTc82zEVIcO3615iIZFeAx5NaDvVNexUsgXuDy2XMN6gyi5yOBuZI4FzGwj8nhQQ75vyF2ICTm/IQ38OuEw/2suXWvSb
      F9HCWk4BASmLXPb4IbbWdXGDAa8aHXm3baNX/o/RSS55H8BWqpmcvR8B4Zqm8cqkMGa48PaenKMTXVXOQmWIWTtOZaZSg77lmNG1/0c+a4UXp176xKiNuB/ZT7XVK0Ta7qwii/HtzvCCLU="
    - secure: "FPqM7uoQ4zGi29/4ABQA01OftnX6m9Z3AcP1h8UlDW19F1aYCrjF6gUFEULgK12TCMVvDtSUSVC5g7NbGLCXtY+Y7HbFi9JgosPJRnXBorncfWwrueEJOsIp986IiBOpgRWymT63zL84wOd1g9AYesXY2BZYJYf6XrJeI3SEGquoF
      mBUDE3ACulFE49ry0W1rSLE2c9e6zJvzGZUi9rUfdm2unBINbK93/YuSl8evsXjQeXx6ZgR5pcKUUaL+7Lrz8+/TDJyit9QSFZS1Qb3vTVLCMKlOWgPvQ9wWD/Yv5spZ3YnHK9sOmENwrCuwBtqx2CYbQfCXu0UjptjYz+0vlcqd5FodfTzg7HBl
      s/1Qf6ptVnOLJoXx6iojpfQp6Ay0c15NzMOEFsxi4fyzBz3Wpjfybs+3j8+cApDDoQfLKpNDUHHAgkyT4yX/JXf69F30CKOihcbnEIXNpFetzfv/JAzm/V7xEOR2hXkMvENvLEBJcFig1yJhfF5cYtWuakM5R03KRhQb1B0Mv23iONqPf1imby1U
      iDuE32LvFry36deDAMHZorkKnRp2ST6DiGfG7SAXgA9qxAb6Lo3i0OuY51j1tP7Au+nR2LllieJE4p1vu7rhBlDreMnjT9vnwYtPprntazHgbLDL7p2CgnJWlbYk1BYcB+jAJc/oJhwkag="
