language: java
jdk:
  - openjdk8
install:
  - mvn --settings bin/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
before_install:
  - export TZ=Asia/Shanghai
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
cache:
  directories:
    - $HOME/.m2/repository
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
stages:
  - build
  - name: release
    if: tag =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/
jobs:
  include:
    - stage: release
      name: "maven install release"
      script: echo "Deploying to GitHub releases ..." && pwd
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        on:
          tags: true
after_deploy:
  - bin/deploy.sh
