language: java
jdk:
  - openjdk8
install:
  - mvn --settings bin/settings.xml install -DskipTests=true  -Dmaven.javadoc.skip=true -B -V
before_install:
  - openssl aes-256-cbc -K $encrypted_81c98acad902_key -iv $encrypted_81c98acad902_iv -in bin/codesigning.asc.enc -out bin/codesigning.asc -d
  - export TZ=Asia/Shanghai
cache:
  directories:
    - $HOME/.m2/repository
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
stages:
  - build
  - name: release
    if: tag =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/
jobs:
  include:
    - stage: release
      name: "maven install release"
      script: echo "Deploying to GitHub releases ..." && pwd
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        on:
          tags: true
after_deploy:
  - bin/deploy.sh
